export const MEETINGS_GET_MEETINGS_BEGIN = 'MEETINGS_GET_MEETINGS_BEGIN';
export const MEETINGS_GET_MEETINGS_SUCCESS = 'MEETINGS_GET_MEETINGS_SUCCESS';
export const MEETINGS_GET_MEETINGS_FAILURE = 'MEETINGS_GET_MEETINGS_FAILURE';
export const MEETINGS_GET_MEETINGS_DISMISS_ERROR = 'MEETINGS_GET_MEETINGS_DISMISS_ERROR';
